#! /bin/bash
if [ $1 = -w ] ; then

  echo "update -w for windows env"

  echo "#update cp -f ../git/.gitconfig_win ~/.gitconfig"
  \cp -f ../git/.gitconfig_win ~/.gitconfig
	
  echo "update cp ../git/.gitignore ~"
  \cp -f ../git/.gitignore ~

  #By include bash_profile
  #echo "############">>/etc/profile
  #echo "Add by dsjin">>/etc/profile
  #echo "export LESSCHARSET=utf-8">>/etc/profile

  echo "############">>/etc/inputrc
  echo "#Add by dsjin">>/etc/inputrc
  echo "set output-meta on">>/etc/inputrc
  echo "set convert-meta off">>/etc/inputrc
  dos2unix /etc/inputrc

  echo "#update cp -f ../git/extDiff_win /bin/extDiff"
  \cp -f ../git/extDiff_win /bin/extDiff

  echo "#update cp -f ../git/extDiffMerge_win /bin/extDiffMerge"
  \cp -f ../git/extDiffMerge_win /bin/extDiffMerge

  echo "#update cp -f ../git/bash_profile_win ~/.bashrc"
  \cp -f ../git/bash_profile_win ~/.bashrc


  echo "#update cp -f ../vim/.vimrc_win /c/Program\ Files/Vim/_vimrc"
  \cp -f ../vim/.vimrc_win /c/Program\ Files/Vim/_vimrc

  echo "#update supertab.vim for All language"
  \cp -f ../vim/supertab.vim /c/Program\ Files/Vim/vim7*/plugin

  echo "#update code_complete.vim for C language"
  \cp -f ../vim/code_complete.vim /c/Program\ Files/Vim/vim7*/plugin

  #echo "#update ctags ver5.8 for C language --> vim.exe dir"
  #\cp -f ../vim/ctags58/ctags58/ctags.exe /c/Program\ Files/Vim/vim7*

  echo "#update taglist.vim (common ctags)"
  \cp -f ../vim/taglist_45/plugin/taglist.vim /c/Program\ Files/Vim/vim7*/plugin

  echo "#update taglist.txt for doc (common ctags)"
  \cp -f ../vim/taglist_45/doc/taglist.txt /c/Program\ Files/Vim/vim7*/doc

  echo "#update verilog_plugin "
  \cp -f ../vim/verilog_plugin.vim /c/Program\ Files/Vim/vim7*/plugin

  echo "#update verilog_plugin_1 "
  \cp -f ../vim/verilog_plugin_1.vim /c/Program\ Files/Vim/vim7*/plugin

  echo "#update c-support for C/C++ code "
  \cp -fr ../vim/cvim/* /c/Program\ Files/Vim/vimfiles

  echo "#update make.exe for windows -->/bin/"
  \cp -fr ./make.exe /bin/

  echo "#update ctags.exe for windows -->/bin/"
  \cp -fr ./ctags.exe /bin/

  echo "#update softbluev2 Color"
  \cp -fr ../vim/softbluev2.vim /c/Program\ Files/Vim/vim7*/plugin

elif [ $1 = -l ] ; then

  echo "update -l for linux env"

  echo "update cp ../bash/.bashrc_linux ~/.bashrc"
  \cp -f ../bash/.bashrc_linux ~/.bashrc
  
  echo "update cp ../vim/.vimrc_linux ~/.vimrc"
  \cp -f ../vim/.vimrc_linux ~/.vimrc


  echo "update cp ../git/.gitconfig_linux ~/.gitconfig"
  \cp -f ../git/.gitconfig_linux ~/.gitconfig

  echo "update cp ../git/.gitignore ~"
  \cp -f ../git/.gitignore ~

  echo "update cp ../git/extDiff_linux /usr/local/bin"
  \cp -f ../git/extDiff_linux /usr/local/bin/extDiff

  echo "update cp ../git/extDiffMerge_linux /usr/local/bin/extDiffMerge"
  \cp -f ../git/extDiffMerge_linux /usr/local/bin/extDiffMerge

else
  echo "Error option /-w for Window,-l for Linux/"
fi
