
update-in:
	make update-in -f bashrc.Makefile
	
	cd synopsys;\
	make update-in;\
	cd -
	
	cd mentor;\
	make update-in;\
	cd -
	
	cd cadence;\
	make update-in;\
	cd -

update-to:
	make update-to -f bashrc.Makefile
	
	cd synopsys;\
	make update-to;\
	cd -
	
	cd mentor;\
	make update-to;\
	cd -
	
	cd cadence;\
	make update-to;\
	cd -

