
update-in:
	\cp -rf ~/.cdsinit ./IC5141_lnx86.cdsinit
	\cp -rf ~/.cdsenv ./IC5141_lnx86.cdsenv
	\cp -rf /ecad/cadence/IC5141_lnx86/tools/dfII/local/.cdsinit ./IC5141_lnx86.cdsinit.calibre
	\cp -rf /ecad/cadence/IC5141_lnx86.bashrc ./IC5141_lnx86.bashrc

update-to:
	\cp -rf IC5141_lnx86.cdsinit ~/.cdsinit
	\cp -rf IC5141_lnx86.cdsenv ~/.cdsenv
	\cp -rf IC5141_lnx86.cdsinit.calibre /ecad/cadence/IC5141_lnx86/tools/dfII/local/.cdsinit
	\cp -rf IC5141_lnx86.bashrc /ecad/cadence/IC5141_lnx86.bashrc

