#! /bin/perl  -w
if (($ARGV[0] ne "-bom") or ($ARGV[2] ne "-price")){
  print "******************************************\n";
  print "*allprice -bom bom_file -price price_file*\n";
  print "******************************************\n";
  exit;
}
else {
  open(F1,"<$ARGV[1]") or die;
  open(F2,"<$ARGV[3]") or die;
  @bom_file=<F1>;
  @price_file=<F2>;
  close F2;
  close F1;

  print @bom_file;
  print @price_file;

  #foreach (@bom_file){
  #}

  # $jin=D1/J1;
  # sub get_price {
  #   foreach (@price_file){
  #     if (m/$_[0]/){
  #       m/price:(.*)/;
  #       print "Price of $_[0] is $1\n";
  #     }
  #   }
  # }
  #sub test {
  #print @_;
  #}
  #&test(@bom_file,@price_file);

  #$a1="D2/1N4007/DO42";
  #$b1="RC";
  #if ($a1=~m/$b1/){
  #print "OK\n";
  #}
  #print "$a1\n";

  sub get_part_type_price {
    foreach my $var (@price_file){
    if (($var=~m/$_[0]/) and ($var=~m/price:([\d\.]+)/)){
      my $price=$1;
      return $price;
    }
    #else{
      #print "Non for $_[0] price information";
      #$1="Non_price";
      #return "Non_price";
      #}
    }
      return "non_price_error";
  }

  #$price=&get_price($a1);
  #print "$price\n";

  #my@array=("tom","dick","harry");
  #@arry[0..9]=((0)x10);//重复10次0
  #my@new_array=@array[1,3,5];
  #@array[1,0]=@array[0,1];
  #@user3=("zk",@user1); #合并数组变量

  print ++$#bom_file."\n";#==>$#bom_file+1 =>22
  #print $#bom_file++;#=================>21
  #for ($var=0,$var<(++$#bom_file),$var++){

  #}

  #Init total_price == 0 value
  $total_price=0;
  $part_type_total_price=0;

  #Get part_type_number part_type part_type_price part_type_total_price
  foreach (@bom_file){
    if (m/\|\d+\s+\|(\d+)\s+\|[\d\w\_\-,]+\s+\|([\w\d\_\-\/]+)\s+/){

      $part_type_number=$1;
      $part_type=$2;
      $part_type_price=&get_part_type_price($part_type);
      #$part_type_total_price=$part_type_number*$part_type_price;
      
      #print "Information---->$part_type\n";
      #print "                $part_type_number\n";
      #print "                $part_type_price\n";
      #print "                $part_type_total_price\n";
      if($part_type_price=~m/non_price_error/){
          print "$part_type is non price information\n";
       }
      else{
      $part_type_total_price=$part_type_number*$part_type_price;
         $total_price+=$part_type_total_price;
       }
     }
  }
  print "Total price is $total_price\n";
}
